services:
  discordjs:
    container_name: botname
    image: boopydoop/botname:latest
    restart: unless-stopped
    logging:
      driver: local
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '0'
          memory: '256M'
