services:
  cobalt-api:
    container_name: cobalt-api
    image: ghcr.io/imputnet/cobalt:10
    restart: unless-stopped
    logging:
      driver: json-file
    init: true
    read_only: true
    ports:
      - "9000:9000"
    environment:
      API_URL: "https://cobalt.servername.co.uk"
      COOKIE_PATH: "/cookies.json"

      # it's recommended to configure bot protection or api keys if the instance is public,
      # see /docs/protect-an-instance.md for more info

      # see /docs/run-an-instance.md for more variables that you can use here

    volumes:
      - ./cookies.json:/cookies.json
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '8G'
