services:
  discordjs:
    container_name: discordjs
    image: discordbot
    restart: unless-stopped
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '0'
          memory: '256M'
