services:
  filepizza:
    container_name: filepizza
    image: kern/filepizza
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "5757:5757"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/filepizza:/config
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    networks:
      default:
        ipv4_address: 100.0.0.14
networks:
  default:
    external: true
    name: yes
