services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data/media:/data/media
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '6G'
        reservations:
          cpus: '0'
          memory: '256M'
    networks:
      default:
        ipv4_address: 100.0.0.3
networks:
  default:
    external: true
    name: yes
