services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/lidarr:/config
      - /data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.12
networks:
  default:
    external: true
    name: yes
