services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/docker/appdata/navidrome:/data:rw"
      - "/data/media/music:/music:ro"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    networks:
      default:
        ipv4_address: 100.0.0.13
networks:
  default:
    external: true
    name: yes
