services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - /docker/appdata/npm/data:/data
      - /docker/appdata/npm/letsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
        reservations:
          cpus: '0.1'
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.3
networks:
  default:
    external: true
    name: yes
