networks:
  appnet:

services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./.data/mongodb:/data/db
    networks:
      - appnet

  server:
    image: 0xfurai/peekaping-server:latest
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
    networks:
      - appnet

  web:
    image: 0xfurai/peekaping-web:latest
    expose: ["80"]
    depends_on:
      - server
    networks:
      - appnet
