x-common:
  panel:
    &panel-environment
    APP_URL: "https://pelican.servername.co.uk" # can be set to 'http://localhost' on port 80 only
    ADMIN_EMAIL: "boopydoop257@gmail.com"

    APP_DEBUG: "false"
    APP_ENV: "production"

  mail:
    &mail-environment
    MAIL_DRIVER: "log"
    # MAIL_HOST: ""
    # MAIL_PORT: ""
    # MAIL_FROM: ""
    # MAIL_USERNAME: ""
    # MAIL_PASSWORD: ""
    # MAIL_SCHEME: ""

services:
  panel:
    container_name: pelican_panel
    image: ghcr.io/pelican-dev/panel:latest
    build: .
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "8009:80"
      - "4443:443"
      - "9000:9000" # enable when not using caddy to be abel to reach php-fpm
    volumes:
      - /docker/appdata/pelican:/pelican-data
      - /docker/appdata/pelican/logs:/var/www/html/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      XDG_DATA_HOME: /pelican-data
      SKIP_CADDY: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    networks:
      default:
        ipv4_address: 100.0.0.15

networks:
  default:
    external: true
    name: yes
