services:
  pingvin-share:
    container_name: pingvin_share
    image: ghcr.io/stonith404/pingvin-share
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - 3000:3000
    volumes:
      - /portainer/Files/AppData/Config/pingvin:/opt/app/backend/data
      - /portainer/Files/AppData/Config/pingvin/images:/opt/app/frontend/public/img
    depends_on:
      clamav:
        condition: service_healthy
  clamav:
    restart: unless-stopped
    image: clamav/clamav
