services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/prowlarr:/config
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
        reservations:
          cpus: '0'
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.6
networks:
  default:
    external: true
    name: yes
