version: "3.8"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/radarr:/config
      - /data:/data
    networks:
      default:
        ipv4_address: 100.0.0.5
networks:
  default:
    external: true
    name: yes
