services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/sabnzbd:/config
      - /data/downloads:/data/downloads:rw
     deploy:
      resources:
        limits:
          cpus: '2'
          memory: '8G'
        reservations:
          cpus: '0'
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.5
networks:
  default:
    external: true
    name: yes
