services:
  samba:
    container_name: samba
    image: ghcr.io/servercontainers/samba:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 445:445
    environment:
      ACCOUNT_admin: L6&nA!wt
      ACCOUNT_admin1: y@38Vfn2
      UID_admin: 1000
      UID_admin1: 1001
      SAMBA_VOLUME_CONFIG_mediashare: "[Media]; path=/shares/media; browsable = yes; valid users = admin, admin1; writable = yes; read only = no; guest ok = no"
    volumes:
      - /data:/shares/media
    cap_add:
      - CAP_NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.1'
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.10
networks:
  default:
    external: true
    name: yes
