services:
  samba:
    container_name: samba
    build: .
    image: ghcr.io/servercontainers/samba
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - 445:445
    environment:
      #WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
      NETBIOS_DISABLE: 1

      ACCOUNT_phone: ${phone_pass}
      UID_alice: 1000

      ACCOUNT_pc: ${pc_pass}
      UID_bob: 1001

      SAMBA_VOLUME_CONFIG_media: "[Media]; path=/shares/media; valid users = phone, pc; guest ok = no; read only = no; browseable = yes;  writeable = yes"

    volumes:
      - /data:/shares/media
    cap_add:
      - CAP_NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          memory: '128M'
    networks:
      default:
        ipv4_address: 100.0.0.10
networks:
  default:
    external: true
    name: yes
