services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/appdata/sonarr:/config
      - /data:/data
    networks:
      default:
        ipv4_address: 100.0.0.6
networks:
  default:
    external: true
    name: yes
