services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      driver: local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
