version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    volumes:
       - /data/compose/68/wordpress:/var/www/html

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${password}
      WORDPRESS_DB_NAME: db

  db:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ${password}
    volumes:
      - ./db_data:/var/lib/mysql

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: --no-autoupdate tunnel run
    environment:
      - TUNNEL_TOKEN=${token}
